### ISSUE TITLE
boost headers not found ?

### ISSUE THREAD

**Issue by mouaret** [SimonCROS/push_swap_tester#4]
Hi,
I wanted to give the tester a try. Unfortunately I could not Make it, as main uses <boost> libraries.
I don't know what's the best way to address it without spending much time fixing the boos libraries on my 42-station ;-)

many thanks in advance,
M

**Comment by SimonCROS** [comment]
Oh, I'm so sorry, I just saw your issue 😕.
I'll fix it today.

**Comment by mouaret** [comment]
Works fine ! Thank you for taking the time to fix it.
